### ISSUE TITLE
最好加入season_type字段

### ISSUE THREAD

**Issue by yujincheng08** [djytw/BiliRoaming#2]
yujincheng08/BiliRoaming@72fb534

看这个commit。

这样的话一些电影才能生效，不然biliplus不返回解析的。

**Comment by yujincheng08** [comment]
Besides, using `module=pgc` instead of `module=bangumi` when getting `playurl` will solve some problems of movies.

**Comment by djytw** [comment]
谢谢！ 我最近比较忙，可能来不及修复。如果你不介意的话，我在readme里面加个链接到你的fork

**Comment by yujincheng08** [comment]
@djytw 可以哒
